# Generated by Django 5.2.7 on 2025-11-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_visitor_id_visitor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
