# Generated by Django 5.2.7 on 2025-11-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_queue_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='avg_wait_seconds',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
