# Generated by Django 5.2.7 on 2025-11-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_center_avg_wait_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='avg_wait_seconds',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6, null=True),
        ),
    ]
