# Generated by Django 5.2.7 on 2025-11-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_center_avg_wait_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
