# Generated by Django 5.2.7 on 2025-11-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_visitor_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='token_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queue',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
