# Generated by Django 5.2.7 on 2025-11-13 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.center')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.visitor')),
            ],
            options={
                'unique_together': {('center', 'visitor')},
            },
        ),
    ]
