# Generated by Django 5.2.7 on 2025-11-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
