# Generated by Django 5.2.7 on 2025-10-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_center'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_center',
            new_name='is_center_manager',
        ),
    ]
