# Generated by Django 5.2.7 on 2025-11-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_managerotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managerotp',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
